/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-29 09:07:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class carritoCompras_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    HttpSession objSesion=request.getSession(false);
    String usuario=(String)objSesion.getAttribute("usuario");
    if(usuario.equals("")){
        response.sendRedirect("index.jsp");
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\r\n");
      out.write("        <title> Cenadurí­a La Palmera </title>\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"./images/logoPalmera.PNG\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\">\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("        <!-- FONT ICONS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"fonts/icons-linear.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"fonts/icons-fontawesome/css/all.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"cartStyle.css\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        \r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"js/jquery.js\"></script>\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("        <script src=\"contactform/contactform.js\"></script>\r\n");
      out.write("        <script src=\"js/menuscript.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- comment -->\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"container psr\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"header_default\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"site-branding\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"logo\">\r\n");
      out.write("                            <img src=\"images/logoPalmera.PNG\" alt=\"\" class=\"logo-1\">\r\n");
      out.write("                            <img src=\"images/logoPalmera.PNG\" alt=\"\" class=\"logo-2\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"header-right\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"site-navwrap\">\r\n");
      out.write("                            <div class=\"navicons\">\r\n");
      out.write("                                <a href=\"javascript:void;\" class=\"navshow\">\r\n");
      out.write("                                    <span class=\"lnr lnr-menu\"></span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"javascript:void;\" class=\"navhide\">\r\n");
      out.write("                                    <span class=\"lnr lnr-cross\"></span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"sitenav\" id=\"sitenav\">\r\n");
      out.write("                                <div class=\"navwrap\">\r\n");
      out.write("                                    <div class=\"navouter\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <nav class=\"headermenu leftmenu\" id=\"headnav\" role=\"navigation\">\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><a href=\"menu.jsp\">Regresar al menú</a></li>\r\n");
      out.write("                                                <li><a>Hola ");
      out.print( usuario);
      out.write("</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </nav>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--sitenav-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--site-navwrap-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--header_default-->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- HEADER -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container px-3 my-5 clearfix\">\r\n");
      out.write("            <!-- Shopping cart table -->\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                    <h2>Carrito de compra</h2>\r\n");
      out.write("                    <br clear=\"all\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"table table-bordered m-0\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <!-- Set columns width -->\r\n");
      out.write("                                    <th class=\"text-center py-3 px-4\" style=\"min-width: 400px;\">Nombre del platillo</th>\r\n");
      out.write("                                    <th class=\"text-right py-3 px-4\" style=\"width: 100px;\">Precio</th>\r\n");
      out.write("                                    <th class=\"text-center py-3 px-4\" style=\"width: 120px;\">Cantidad</th>\r\n");
      out.write("                                    <th class=\"text-right py-3 px-4\" style=\"width: 100px;\">Total</th>\r\n");
      out.write("                                    <th class=\"text-center align-middle py-3 px-0\" style=\"width: 40px;\"><a href=\"#\" class=\"shop-tooltip float-none text-light\" title=\"\" data-original-title=\"Clear cart\"><i class=\"ino ion-md-trash\"></i></a></th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("\r\n");
      out.write("                                <!-- ADAPTAR PARA QUE DESPLIEGUE LOS ARTICULOS DEL CARRITO-->\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"p-4\">\r\n");
      out.write("                                        <div class=\"media align-items-center\">\r\n");
      out.write("                                            <img src=\"https://bootdey.com/img/Content/avatar/avatar1.png\" class=\"d-block ui-w-40 ui-bordered mr-4\" alt=\"\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <a href=\"#\" class=\"d-block text-dark\">CHIMICHANGAS</a>                                               \r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"text-right font-weight-semibold align-middle p-4\">$57.55</td>\r\n");
      out.write("                                    <td class=\"align-middle p-4\"><input type=\"text\" class=\"form-control text-center\" value=\"2\"></td>\r\n");
      out.write("                                    <td class=\"text-right font-weight-semibold align-middle p-4\">$115.1</td>\r\n");
      out.write("                                    <td class=\"text-center align-middle px-0\"><a href=\"#\" class=\"shop-tooltip close float-none text-danger\" title=\"\" data-original-title=\"Remove\">×</a></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- / Shopping cart table -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"d-flex flex-wrap justify-content-between align-items-center pb-4\">\r\n");
      out.write("                        <div class=\"mt-4\">\r\n");
      out.write("                            <label class=\"text-muted font-weight-normal\">Subtotal: </label><strong>$20</strong>                             \r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <div class=\"text-right mt-4 mr-5\">\r\n");
      out.write("                                    <label class=\"text-muted font-weight-normal m-0\">IVA:  </label><strong>$20</strong>                                \r\n");
      out.write("                                    <div class=\"text-right mt-4\">\r\n");
      out.write("                                        <label class=\"text-muted font-weight-normal m-0\">Total:  </label><strong>$1164.65</strong>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                             \r\n");
      out.write("                            <div class=\"container mt-3\">\r\n");
      out.write("  <h3>Fading Modal Example</h3>\r\n");
      out.write("  <p>Click on the button to open the modal.</p>\r\n");
      out.write("  \r\n");
      out.write("  <button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#myModal\">\r\n");
      out.write("    Open modal\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">Modal Heading</h4>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        Modal body..\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    // Ventana modal\r\n");
      out.write("                    var modal = document.getElementById(\"ventanaModal\");\r\n");
      out.write("                    // Botón que abre el modal\r\n");
      out.write("                    var boton = document.getElementById(\"abrirModal\");\r\n");
      out.write("                    // Hace referencia al elemento <span> que tiene la X que cierra la ventana\r\n");
      out.write("                    var span = document.getElementsByClassName(\"cerrar\")[0];\r\n");
      out.write("\r\n");
      out.write("                    boton.addEventListener(\"click\", function () {\r\n");
      out.write("                        modal.style.display = \"block\";\r\n");
      out.write("                    });\r\n");
      out.write("                    // Si el usuario hace clic en la x, la ventana se cierra\r\n");
      out.write("                    span.addEventListener(\"click\", function () {\r\n");
      out.write("                        modal.style.display = \"none\";\r\n");
      out.write("                    });\r\n");
      out.write("                    // Si el  usuario hace clic fuera de la ventana, se cierra.\r\n");
      out.write("                    window.addEventListener(\"click\", function (event) {\r\n");
      out.write("                        if (event.target == modal) {\r\n");
      out.write("                            modal.style.display = \"none\";\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                </script>\r\n");
      out.write("\r\n");
      out.write("                <footer>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"copyright\">\r\n");
      out.write("                            Copyright &copy; <span id=\"copyrightyear\"></span> Equipo Aplicaciones Web\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </footer>\r\n");
      out.write("                <!-- FOOTER -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </body>\r\n");
      out.write("                </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
